### PR TITLE
Introduce point to line segment distance calculation

### PR DESCRIPTION
**Pull request by zmiao**
This pr introduces a new function `pointToSegmentDistance` for helping calculation of the shortest distance from a point to a line segment.

### CODE REVIEW

**Comment by zmiao** [comment]
@mourner I use turf/point-line-distance as reference of my test, but ,there are three big differences between the actual values and the reference, which causes the unit test failure. 
I checked the source code of turf, they basically use harversin formula to calculate the distance of two points. For CheapRuler, we use the ` FCC prescribed formulae`, I count the kx, ky value to my intermediate vector also. So from your pov, how should we handle the differences?

**Review by mourner — CHANGES_REQUESTED** [review]
Nice addition! There's an existing `pointOnLine` method which does essentially the same calculation but on a polyline. Can we take a portion of it (e.g. cut it out into `pointToSegmentSquared`) as a base and reuse it in both places?

**Comment by zmiao** [comment]
@mourner , I didn't realized that we had the calculation there. I will refactor it. Thank you!

**Comment by mourner** [comment]
For reference, here's an equivalent change in the JS version: https://github.com/mapbox/cheap-ruler/commit/2f684336d1d07e7228a220a60984541eb1877508

**Comment by zmiao** [comment]
Thanks @mourner! Adaptation is done, please review.

**Review by mourner — APPROVED** [review]
Well done!

**Pull request merged**
